include:
  - docker-compose-monitor.yml

services:
  backend:
    build:
      context: ../matatani-backend
      dockerfile: Dockerfile
    image: matatani-backend:1.0
    container_name: matatani-backend
    ports:
      - "8080:8080"
    depends_on:
      - minio
    networks:
      - app-network
    env_file:
      - path: ./.env
        required: true

  tusd:
    image: tusproject/tusd:latest
    command: -s3-endpoint=http://minio:9000
      -s3-bucket=${S3_BUCKET}
      -s3-object-prefix=uploads/
      -hooks-grpc=${BACKEND_GRPC_URL}
      -host=0.0.0.0
      -port=1080
    env_file:
      - path: ./.env
        required: true
    ports:
      - "1080:1080"
    networks:
      - app-network
    depends_on:
      - backend
      - minio

  minio:
    image: minio/minio:latest
    container_name: matatani-minio
    ports:
      - "9100:9000"
      - "9101:9001"
    volumes:
      - minio-data:/data
    env_file:
      - path: ./.env
        required: true
    command: server /data --console-address ":9001"
    networks:
      - app-network

  frontend:
    build:
      context: ../matatani-frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    image: matatani-frontend:1.0
    container_name: matatani-frontend
    ports:
      - "${FE_PORT}:${FE_PORT}"
    env_file:
      - path: ./.env
        required: true
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  minio-data:
